# Generated by Django 5.1.4 on 2026-04-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrisense', '0005_teamapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='AgriSense Tutorial', help_text='Video title displayed in modal', max_length=200)),
                ('youtube_url', models.URLField(help_text='YouTube embed URL (e.g., https://www.youtube.com/embed/VIDEO_ID)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Show this video on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tutorial Video',
                'verbose_name_plural': 'Tutorial Videos',
            },
        ),
    ]
