# Generated by Django 5.1.4 on 2026-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrisense', '0006_tutorialvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialvideo',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='tutorialvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4 video file (max 1GB)', null=True, upload_to='tutorial_videos/'),
        ),
        migrations.AlterField(
            model_name='tutorialvideo',
            name='title',
            field=models.CharField(default='AgriSense Tutorial', help_text='Video title', max_length=200),
        ),
    ]
