# Generated by Django 5.2.5 on 2026-04-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrisense', '0007_remove_tutorialvideo_youtube_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantscan',
            name='crop_type_ur',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plantscan',
            name='disease_name_ur',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plantscan',
            name='severity_ur',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='plantscan',
            name='treatment_recommended_ur',
            field=models.TextField(blank=True),
        ),
    ]
