# Generated by Django 5.2.5 on 2026-04-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrisense', '0008_plantscan_crop_type_ur_plantscan_disease_name_ur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamapplication',
            name='name_ur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Full Name (Urdu)'),
        ),
        migrations.AddField(
            model_name='teamapplication',
            name='role_ur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Desired Role (Urdu)'),
        ),
    ]
