# Generated by Django 5.2.5 on 2026-04-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrisense', '0009_teamapplication_name_ur_teamapplication_role_ur'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Crop name (e.g., Orange, Apple, Corn)', max_length=100, unique=True)),
                ('name_ur', models.CharField(blank=True, help_text='Crop name in Urdu', max_length=100)),
                ('description', models.TextField(help_text='Detailed information about this crop category')),
                ('description_ur', models.TextField(blank=True, help_text='Detailed information in Urdu')),
                ('icon', models.CharField(default='psychology', help_text='Material Symbol icon name', max_length=50)),
            ],
            options={
                'verbose_name': 'Crop Category',
                'verbose_name_plural': 'Crop Categories',
            },
        ),
    ]
