# Generated by Django 5.2.5 on 2026-04-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrisense', '0010_cropcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('dashboard', 'Dashboard'), ('scanner', 'Scanner'), ('history', 'History'), ('about', 'About'), ('profile', 'Profile'), ('settings', 'Settings'), ('global', 'Global/Shared')], default='global', max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('text_en', models.TextField(help_text='Original English text')),
                ('text_ur', models.TextField(blank=True, help_text='Urdu translation')),
            ],
            options={
                'verbose_name': 'Static UI Content',
                'verbose_name_plural': 'Static UI Content',
                'unique_together': {('page', 'key')},
            },
        ),
    ]
