# Generated by Django 5.1.4 on 2026-03-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrisense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantscan',
            name='notification_read',
            field=models.BooleanField(default=False),
        ),
    ]
