# Generated by Django 5.1.4 on 2026-03-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrisense', '0002_plantscan_notification_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='AgriSense', help_text='Name shown in sidebar, header, mobile menu etc.', max_length=60)),
                ('app_subtitle', models.CharField(blank=True, default='Edge Intelligence', help_text='Small text shown below the app name / logo', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Branding',
                'verbose_name_plural': 'Site Branding',
            },
        ),
    ]
